//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NodarbibuSarakstsPR4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NodarbibuSarakstsContainer : DbContext
    {
        public NodarbibuSarakstsContainer()
            : base("name=NodarbibuSarakstsContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Students> StudentsSet { get; set; }
        public virtual DbSet<Lektors> LektorsSet { get; set; }
        public virtual DbSet<Kurss> KurssSet { get; set; }
        public virtual DbSet<Programma> ProgrammaSet { get; set; }
        public virtual DbSet<StudentuGrupa> StudentuGrupaSet { get; set; }
        public virtual DbSet<Nodarbiba> NodarbibaSet { get; set; }
    }
}
