//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NodarbibuSarakstsPR4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nodarbiba
    {
        public int Id { get; set; }
        public System.DateTime Datums { get; set; }
        public System.TimeSpan Sakums { get; set; }
        public System.TimeSpan Beigas { get; set; }
    
        public virtual Kurss Kurss { get; set; }
        public virtual Lektors Lektors { get; set; }
    }
}
